In [4]:
import numpy as np

a= np.random.randint(0,10,10)
a


array([0, 4, 6, 4, 5, 0, 0, 0, 8, 6])

In [8]:
len(a)

10

In [9]:
a.reshape(2,5)

array([[0, 4, 6, 4, 5],
       [0, 0, 0, 8, 6]])

In [14]:
# creating Arrays

In [10]:
a.reshape(10)


array([0, 4, 6, 4, 5, 0, 0, 0, 8, 6])

In [11]:
a[::2]

array([0, 6, 5, 0, 8])

In [17]:
import numpy as np
mylist = [1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

In [19]:
n = np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [22]:
n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [24]:
o=np.linspace(0,4,9)
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [25]:
o.resize(3,3)
o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

In [27]:
np.eye(3)


array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [28]:
np.diag(o)

array([ 0.,  2.,  4.])

In [29]:
np.repeat([1,2,3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [32]:
p =  np.ones([2,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [33]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [34]:
np.hstack([p, 2*p])


array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [35]:
x=np.random.randint(0,10,10)
x

array([7, 9, 5, 4, 8, 7, 7, 3, 6, 4])

In [38]:
x = x.reshape(2,5)
x

array([[7, 9, 5, 4, 8],
       [7, 7, 3, 6, 4]])

In [40]:
y = np.array([1,2,3,4,5])
y

array([1, 2, 3, 4, 5])

In [41]:
x*y


array([[ 7, 18, 15, 16, 40],
       [ 7, 14,  9, 24, 20]])

In [42]:
x+y

array([[ 8, 11,  8,  8, 13],
       [ 8,  9,  6, 10,  9]])

In [44]:
x.dot(y)

array([96, 74])

In [53]:
a = np.array([1,2,3])
b= np.array([[1,2,3], [1,2,3]])
b.dot(a)

array([14, 14])

In [55]:
x.T

array([[7, 7],
       [9, 7],
       [5, 3],
       [4, 6],
       [8, 4]])

In [56]:
x.T.shape

(5, 2)

In [58]:
x.shape

(2, 5)

In [60]:
x.sum()

60

In [62]:
x.std()

1.8439088914585775

In [64]:
x.argmax()

1

In [66]:
x.argmin()

7

In [69]:
y.argmax()

4

In [73]:
y.argmin()

0

In [75]:
x


array([[7, 9, 5, 4, 8],
       [7, 7, 3, 6, 4]])

In [77]:
x.argmin()

7

In [79]:
x.argmax()

1

x